### ISSUE TITLE
Is castling working?

### ISSUE THREAD

**Issue by licaon-kter** [MatthewDorner/mattermost-plugin-chess#10] opened 2020-12-09 16:18 UTC
I can't seem to be able to trigger it.

Ref: https://github.com/jhlywa/chess.js/issues/219

**Comment by MatthewDorner** [comment] 2020-12-10 17:23
It was working back when I tested it last, can you provide a screenshot of a specific game state where if you attempt to castle, it won't work?

**Comment by licaon-kter** [comment] 2020-12-10 17:58
Don't have one now, will make a mockup.

**Comment by Roy-Orbison** [comment] 2021-09-03 00:02
Works for me in current version.

**Comment by MatthewDorner** [comment] 2022-02-28 06:10
Unable to reproduce, users report castling is working in current version. Closing issue.

**Closed as completed by MatthewDorner** 2022-02-28 06:10 UTC
